kind: Template
apiVersion: v1
metadata:
  name: blast-video-template
  annotations:
    description: This example shows how to create application containing multiple micoroservices in openshift origin v3
    iconClass: icon-python
labels:
  template: blast-video
objects:
  #
  # configuration
  #
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: video
    data:
      MONGODB_USER: "${MONGODB_USER}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
      MONGODB_ADMIN_PASSWORD: "${MONGODB_ADMIN_PASSWORD}"
      MONGODB_DATABASE: blast_video
  #
  # build configuration
  #
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: video
      labels:
        name: video
    spec:
      triggers:
        - type: GitHub
          github:
            secret: "${GITHUB_SECRET}"
        - type: Generic
          generic:
            secret: "${GENERIC_SECRET}"
        - type: ImageChange
        - type: ConfigChange
      source:
        type: Git
        git:
          uri: https://github.com/soltysh/blast.git
        contextDir: video
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python:latest
            namespace: openshift
      output:
        to:
          kind: ImageStreamTag
          name: video:latest
  #
  # image stream configuration
  #
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: video
  #
  # deployment configuration
  #
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: video
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - video
            from:
              kind: ImageStreamTag
              name: video:latest
        - type: ConfigChange
      replicas: 1
      selector:
        name: video
      template:
        metadata:
          labels:
            name: video
        spec:
          containers:
            - name: video
              image: video
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /blast/api/v1.0/video/x
                  port: 8080
                  scheme: HTTP
              env:
                - name: MONGODB_USER
                  valueFrom:
                    configMapKeyRef:
                      name: video
                      key: MONGODB_USER
                - name: MONGODB_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: video
                      key: MONGODB_PASSWORD
                - name: APP_MODULE
                  value: api:app
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
  #
  # service configuration
  #
  - kind: Service
    apiVersion: v1
    metadata:
      name: video
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        name: video
  #
  # route configuration
  #
  - kind: Route
    apiVersion: v1
    metadata:
      name: video
    spec:
      to:
        kind: Service
        name: video
  #
  # backend deployment configuration
  #
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: video-db
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
      replicas: 1
      selector:
        name: video-db
      template:
        metadata:
          labels:
            name: video-db
        spec:
          containers:
            - name: video-db
              image: centos/mongodb-32-centos7:latest
              ports:
                - containerPort: 27017
                  protocol: TCP
              env:
                - name: MONGODB_USER
                  valueFrom:
                    configMapKeyRef:
                      name: video
                      key: MONGODB_USER
                - name: MONGODB_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: video
                      key: MONGODB_PASSWORD
                - name: MONGODB_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: video
                      key: MONGODB_DATABASE
                - name: MONGODB_ADMIN_PASSWORD
                  valueFrom:
                    configMapKeyRef:
                      name: video
                      key: MONGODB_ADMIN_PASSWORD
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
  #
  # backend service configuration
  #
  - kind: Service
    apiVersion: v1
    metadata:
      name: video-db
    spec:
      ports:
        - name: web
          protocol: TCP
          port: 27017
          targetPort: 27017
      selector:
        name: video-db
#
# template parameters generation configuration
#
parameters:
  - name: MONGODB_USER
    description: mongodb database username
    generate: expression
    from: "[A-Za-z0-9]{24}"
    required: true
  - name: MONGODB_PASSWORD
    description: mongodb database password
    generate: expression
    from: "[A-Za-z0-9]{24}"
    required: true
  - name: MONGODB_ADMIN_PASSWORD
    description: mongodb database admin password
    generate: expression
    from: "[A-Za-z0-9]{24}"
    required: true
  - name: GITUB_SECRET
    description: github webhook secret
    generate: expression
    from: "[A-Za-z0-9]{24}"
    required: true
  - name: GENERIC_SECRET
    description: generic webhook secret
    generate: expression
    from: "[A-Za-z0-9]{24}"
    required: true
