apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: backend
    name: backend
  name: backend
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: backend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: backend
    git:
      uri: https://github.com/vrutkovs/catcatgo.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.5
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: ${GITHUB_SECRET}
    type: GitHub
  - generic:
      secret: 0ra86DgvrnBWER8lQOAYKSKe
    type: Generic
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
status:
  lastVersion: 0
