apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: blast-scraper-template
    name: scraper
    template: blast-scraper
  name: scraper
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: scraper:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: scraper
    git:
      uri: https://github.com/vrutkovs/catcatgo.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.5
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: ${GITHUB_SECRET}
    type: GitHub
  - generic:
      secret: cymhUQdAjViWaCHSdtPHD7e0
    type: Generic
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
status:
  lastVersion: 0
