apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: ui
  name: ui
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ui:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: ui
    git:
      uri: https://github.com/vrutkovs/catcatgo.git
      ref: istio
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: lighttpd-centos7:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: tD-s18SgLxHmEIMZvLQF
    type: GitHub
  - generic:
      secret: 1FlOnVb2e8OXQWO9ZEcc
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
