apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    run: scraper
  name: scraper
spec:
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: scraper
        spec:
          containers:
          - image: docker-registry.default.svc:5000/catcatgo/scraper
            imagePullPolicy: Always
            name: scraper
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: scraper
          serviceAccountName: scraper
          terminationGracePeriodSeconds: 30
  schedule: 0/30 * * * *
  suspend: false
status:
  lastScheduleTime: 2018-04-28T16:30:00Z
