apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: backend
  name: backend
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: 172.30.16.196:5000/catcatgo/backend:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""
