apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2018-04-28T14:29:51Z
  creationTimestamp: null
  generation: 2
  labels:
    app: hawkular-grafana
  name: hawkular-grafana-datasou
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/imported-from: hawkular/hawkular-grafana-datasource
    from:
      kind: DockerImage
      name: 172.30.16.196:5000/catcatgo/hawkular-grafana-datasou:latest
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
