apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    app: blast-ui-template
    template: blast-ui
  name: ui
spec:
  host: ui-catcatgo.54.175.151.183.xip.io
  to:
    kind: Service
    name: ui
    weight: 100
  wildcardPolicy: None
